# Generated by Django 2.1.7 on 2019-03-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view', 'View course'), ('edit', 'Edit course'))},
        ),
    ]
