# Generated by Django 2.1.7 on 2019-04-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearn', '0002_course_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_id', models.CharField(default='videoid', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='eLearn.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
