# Generated by Django 2.1.7 on 2019-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearn', '0005_remove_video_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.CharField(max_length=100),
        ),
    ]
